package Car;

public enum Optional {
    AIRBAG,
    HYDRAULIC_STEERING_WHEEL,
    ELETRIC_STEERING_WHEEL,
    MANUAL_STEERING_WHEEL,
    LEATHER_SITS,
    ALARM,
    AIR_CONDITIONING,
    HEIGHT_CONTROL_SITS,
    HEATING_SITS,
    ON_BOARD_COMPUTER,
    SPEED_CONTROL,
    TRACTION_CONTROL,
    XENON_HEADLIGHT,
    ABS,
    PHOTOCHROMIC_REAR_VIEW,
    TRACTION_4X4,
    RAIN_SENSOR,
    PARK_SENSOR,
    SUNROOF,
    ELETRIC_LOOKS,
    ELETRIC_WINDOW,
    SIZE_CONTROL_STEERING_WHEEL,
    CD,
    DVD,
    LIGHT_ALLOY_WHEELS;

}
